version: "3"

services:
  app:
    build: .
    container_name: simulator
    volumes:
      - .:/go/src/
    extra_hosts:
      - "docker.for.win.host.internal:172.17.0.1"
networks:
  default:
    external:
      name: apache-kafka_default